name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack --no-restore
    - name: Publish NuGet
      run: dotnet nuget push **/*.nupkg  --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN} --no-symbols true
      env:
         NUGET_TOKEN: ${{secrets.PUBLIC_NUGET_TOKEN}}

    - name: Publish Proget
      run: dotnet nuget push **/*.nupkg --source ${NUGET_SOURCE} --api-key ${NUGET_KEY} --no-symbols true
      env:
         NUGET_SOURCE: ${{secrets.PROGET_NUGET}}
         NUGET_KEY: ${{secrets.PROGET_NUGET_TOKEN}}  
    # - name: release
    #  uses: actions/create-release@v1
    #  id: create_release
    #  with:
    #    draft: false
    #    prerelease: false
    #    release_name: ${GitBuildVersionSimple}
    #    tag_name: ${GitBuildVersionSimple}
    #  env:
    #    GITHUB_TOKEN: ${{ github.token }}     
